"""Axiom: deterministic market research and strategy evolution."""

from .domain import (
    CryptoTicker,
    Fill,
    InstrumentMetadata,
    MarketType,
    OHLCVBar,
    OrderBookLevel,
    OrderBookSnapshot,
    OrderType,
    PredictionMarketSnapshot,
    ResolvedContract,
    SettlementState,
    Side,
    SimulationQuality,
    TradePrint,
)
from .attribution import fitness_attribution
from .benchmarks import BenchmarkResult, crypto_benchmarks, prediction_benchmarks
from .collector import CollectionCycle, CollectorConfig, PolymarketCollector
from .dashboard import DashboardData, DashboardServer, create_dashboard_server
from .domain import ResearchQuality
from .forward import ForwardTestRegistry, ForwardTestSpec
from .opportunity import Opportunity, scan_opportunities
from .robustness import (
    bootstrap_confidence_interval,
    minimum_sample_check,
    multiple_testing_summary,
    neighboring_parameter_stability,
)
from .storage import AxiomStore
from .data import (
    BinanceAdapter,
    CryptoMarketDataProvider,
    DataPipeline,
    InMemoryCryptoProvider,
    InMemoryPredictionProvider,
    IngestionReport,
    MarketDataPipeline,
    PolymarketAdapter,
    PredictionMarketDataProvider,
    SyntheticCryptoProvider,
    SyntheticPredictionProvider,
)
from .strategy import StrategyDefinition, StrategyDSL, StrategySpec, StrategyValidationError, load_strategy, validate_strategy, evaluate_signal
from .portfolio import OrderRequest, OrderState, Portfolio, Position
from .backtest import BacktestResult, CryptoBacktester, CryptoOHLCVBacktester, PredictionBacktester, PredictionMarketBacktester, PredictionMarketHistoricalSimulator
from .metrics import (
    brier_score,
    calibration_buckets,
    calibration_at_horizons,
    calculate_crypto_metrics,
    calculate_prediction_metrics,
    calmar_ratio,
    conditional_value_at_risk,
    cvar,
    drawdown_series,
    ece,
    expected_calibration_error,
    expected_shortfall,
    expected_value,
    log_loss,
    longest_losing_streak,
    max_drawdown,
    prediction_expected_value,
    profit_factor,
    sharpe_ratio,
    sortino_ratio,
)
from .risk import RiskDecision, RiskEngine, RiskLimits, fractional_kelly_size
from .regime import Regime, RegimeEngine, RegimeSnapshot, RegimeState
from .evolution import EvolutionCandidate, EvolutionEngine, EvolutionResult
from .evaluation import DatasetPartition, DatasetSplit, EvaluationResult, dataset_version, split_dataset, walk_forward_splits
from .tracking import ExperimentRecord, ExperimentTracker, TrackingService
from .probability import (
    BaseRateModel,
    BayesianBelief,
    BetaBelief,
    CryptoPriceTargetModel,
    DEFAULT_PROBABILITY_MODELS,
    ProbabilityEstimate,
    ProbabilityModelRegistry,
)
from .hermes import CandidateMessage, Hermes, HermesPermissions, HermesValidationError, HypothesisMessage, ReportMessage
from .paper import CryptoPaperTrader, LiveExecutionDisabled, PaperTradingConfig, PredictionPaperTrader
from .node import NodeConfig, ResearchNode
from .paper_engine import ForwardPaperEngine, PaperEngineCycle, historical_replay_id, run_forward_paper, run_historical_replay
from .lifecycle import CandidateLifecycle, CandidateLifecycleManager, CandidateStage, PromotionCriteria
from .mutations import DeterministicMutationEngine, ExperimentBudget, MutationCandidate
from .research_bus import DurableResearchBus, ResearchBusPermissionError, ResearchQueueItem, ResearchQueueStatus
from .director import ProposalValidation, compact_report, research_summary, validate_hermes_proposal
from .research import ResearchReport, run_crypto_research, run_initial_research, run_prediction_research, write_report

__all__ = [
    "DashboardData",
    "DashboardServer",
    "AxiomStore",
    "BenchmarkResult",
    "CollectionCycle",
    "CollectorConfig",
    "ForwardTestRegistry",
    "ForwardTestSpec",
    "Opportunity",
    "PolymarketCollector",
    "ResearchQuality",
    "bootstrap_confidence_interval",
    "calibration_at_horizons",
    "crypto_benchmarks",
    "BacktestResult",
    "BayesianBelief",
    "BetaBelief",
    "BinanceAdapter",
    "CryptoTicker",
    "CryptoOHLCVBacktester",
    "CandidateMessage",
    "CryptoBacktester",
    "CryptoMarketDataProvider",
    "DataPipeline",
    "IngestionReport",
    "MarketDataPipeline",
    "EvolutionCandidate",
    "DatasetPartition",
    "DatasetSplit",
    "EvaluationResult",
    "EvolutionEngine",
    "EvolutionResult",
    "CandidateLifecycle",
    "CandidateLifecycleManager",
    "CandidateStage",
    "PromotionCriteria",
    "DeterministicMutationEngine",
    "ExperimentBudget",
    "MutationCandidate",
    "ForwardPaperEngine",
    "PaperEngineCycle",
    "run_forward_paper",
    "run_historical_replay",
    "historical_replay_id",
    "DurableResearchBus",
    "ResearchBusPermissionError",
    "ResearchQueueItem",
    "ResearchQueueStatus",
    "ProposalValidation",
    "compact_report",
    "research_summary",
    "validate_hermes_proposal",
    "ExperimentRecord",
    "ExperimentTracker",
    "Fill",
    "Hermes",
    "HermesPermissions",
    "HermesValidationError",
    "HypothesisMessage",
    "InMemoryCryptoProvider",
    "InMemoryPredictionProvider",
    "InstrumentMetadata",
    "CryptoPaperTrader",
    "LiveExecutionDisabled",
    "MarketType",
    "BaseRateModel",
    "CryptoPriceTargetModel",
    "DEFAULT_PROBABILITY_MODELS",
    "ProbabilityEstimate",
    "ProbabilityModelRegistry",
    "OHLCVBar",
    "OrderBookLevel",
    "OrderBookSnapshot",
    "OrderRequest",
    "OrderState",
    "PaperTradingConfig",
    "NodeConfig",
    "ResearchNode",
    "PolymarketAdapter",
    "Portfolio",
    "Position",
    "PredictionMarketBacktester",
    "PredictionMarketDataProvider",
    "PredictionMarketSnapshot",
    "PredictionPaperTrader",
    "Regime",
    "RegimeEngine",
    "RegimeSnapshot",
    "RegimeState",
    "ReportMessage",
    "ResearchReport",
    "run_crypto_research",
    "fitness_attribution",
    "minimum_sample_check",
    "multiple_testing_summary",
    "neighboring_parameter_stability",
    "scan_opportunities",
    "prediction_benchmarks",
    "run_initial_research",
    "run_prediction_research",
    "write_report",
    "ResolvedContract",
    "RiskDecision",
    "RiskEngine",
    "RiskLimits",
    "SettlementState",
    "Side",
    "SimulationQuality",
    "StrategyDefinition",
    "StrategyDSL",
    "StrategySpec",
    "load_strategy",
    "StrategyValidationError",
    "SyntheticCryptoProvider",
    "SyntheticPredictionProvider",
    "TradePrint",
    "calmar_ratio",
    "conditional_value_at_risk",
    "cvar",
    "TrackingService",
    "brier_score",
    "calibration_buckets",
    "calculate_crypto_metrics",
    "calculate_prediction_metrics",
    "create_dashboard_server",
    "ece",
    "dataset_version",
    "drawdown_series",
    "evaluate_signal",
    "expected_calibration_error",
    "expected_shortfall",
    "longest_losing_streak",
    "expected_value",
    "fractional_kelly_size",
    "log_loss",
    "max_drawdown",
    "PredictionBacktester",
    "PredictionMarketHistoricalSimulator",
    "profit_factor",
    "prediction_expected_value",
    "sharpe_ratio",
    "sortino_ratio",
    "split_dataset",
    "validate_strategy",
    "walk_forward_splits",
]

